config/routes.rb
UserGroup::Engine.routes.draw do
  get '/',      to: 'static#home'
  get '/help',  to: 'static#help'
  get '/home',  to: 'static#home'
  get '/admin', to: 'static#admin'

  #root :to => 'static#home'

  devise_for :users, {
    :skip => [:registration, :omniauth_callbacks],
    class_name:     'UserGroup::User',
    module: :devise,
  }

  resources :users do
    get 'page/:page', :action => :index, :on => :collection
    member do
      post :create_token
      delete :destroy_token
    end
  end

  resources :groups do
    member do
        put :lock
        get :manage
    end

  end

  resources :memberships, only: [:create, :destroy] do
    member do
        put :approve
        put :approve_read
        delete :remove_read
    end
    collection do
        post :pending
    end
  end

end

app/models/user_group/user.rb
module UserGroup
  class UserGroup::User < ActiveRecord::Base
    has_paper_trail :ignore => [:updated_at, :current_sign_in_at, :last_sign_in_at, :current_sign_in_ip, :last_sign_in_ip, :sign_in_count]
    include UserGroup::UserSecurity
    include UserGroup::UserOptions

    scope :by_letter, ->(initial) { where("second_name LIKE \'#{initial}%\'").order(:second_name) }

    def self.create_for_shibboleth(access_token)
      u = UserGroup::User.new
      u.apply_omniauth(access_token)
      u.skip_confirmation!
      u
    end

  end
end

app/controllers/user_group/users_controller.rb
require_dependency "user_group/application_controller"

module UserGroup
  class UsersController < ApplicationController
    before_action :set_initials, only: [:index]
    before_filter :authenticate_user!, except: [:new, :create, :show]
    #:can_modify (through can_modify_base) also sets @user
    before_filter :can_modify, only: [:edit, :update, :destroy, :create_token, :destroy_token]
    before_filter :can_view_profile, only: [:show]

    def index
      # default to index view
      @view = params[:view].present? ? params[:view] : 'index'

      if signed_in and current_user.is_admin?
        if @view == "report"
          @audit = PaperTrail::Version.order('created_at ASC').all
        else
          if params[:user_letter]
            @users = User.by_letter(params[:user_letter]).order(SETTING_ORDER_USER).page(params[:page])
          else
            @users = User.order(SETTING_ORDER_USER).page(params[:page])
          end
        end
      else
        #Must be logged in so show all users that are public/registered
        @users = User.where(:view_level => SETTING_PROFILE_INDEX_VIEW_LEVELS).order(SETTING_ORDER_USER).page(params[:page])
      end
      @users
    end

    def show
    end

    def new
      @user = User.new
      
      if session[:omniauth]
        @user.apply_omniauth(session[:omniauth])
      end
    end

    def create
      @user = User.new(user_params)

      if session[:omniauth]
        @user.apply_omniauth(session[:omniauth])
      end

      if @user.valid? && @user.save
        #Join group registered
        group = UserGroup::Group.find_by_name(SETTING_GROUP_DEFAULT)
        if group.nil?
          group = UserGroup::Group.where(name: SETTING_GROUP_DEFAULT, description: "Every user account is a member of this group.", is_locked: true).first_or_create
        end
        group_id = group.id
        if group_id.nil?
          logger.error("ERROR @ SignUp:: group "+SETTING_GROUP_DEFAULT+" does NOT exist")
        else
          membership = @user.join_group(group_id)
          membership.approve_membership(@user.id)
          membership.save
        end

        if user_signed_in? && current_user.is_admin?
          flash[:success] = I18n.t("user_groups.users.account_created")
          redirect_to @user
        else
          sign_in @user
          flash[:success] = I18n.t("user_groups.users.signup")
          redirect_to @user
        end
      else
        render 'new'
      end

      session[:omniauth] = nil unless @user.new_record?
    end

    def edit
    end

    def update
      current_password = params[:user].delete(:current_password)
      if modifying_current_user?(@user) || !current_user.is_admin?
        unless !@user.password_required? || @user.valid_password?(current_password)
          flash[:error] = I18n.t("user_groups.users.wrong_password")
          redirect_to :back
          return
        end
      end
      #Remove password if not being updated
      if (params[:user].has_key?(:password) && params[:user][:password].empty?) && (params[:user].has_key?(:password_confirmation) && params[:user][:password_confirmation].empty?)
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
      #Update user
      if @user.update_attributes(user_params)
        flash[:success] = I18n.t("user_groups.shared.updated")
        (sign_in @user, bypass: true) if modifying_current_user?(@user)
        redirect_to @user
      else
        render 'edit'
      end
    end

    def destroy
      deleting_user = User.find(params[:id])
      is_current_user = modifying_current_user?(deleting_user)

      deleting_user.destroy

      if is_current_user
        flash[:success] = I18n.t("user_groups.users.deleted_self")
        redirect_to main_app.new_user_session_url
      else
        redirect_to users_url

        flash[:success] = I18n.t("user_groups.users.deleted")
      end
    end

    #Currently anyone who is logged in can create a token on their account
    def create_token
      @user.create_token
      @user.save
      redirect_to @user
      flash[:success] = I18n.t("user_groups.users.token")
    end

    def destroy_token
      @user.destroy_token
      if @user.save
        flash[:success] = I18n.t("user_groups.users.deleted_token")
        redirect_to @user
      else
        render 'edit'
        flash[:error] = I18n.t("user_groups.users.errors.deleted_token")
      end
    end

    private
    def user_params
      params.require(:user).permit(:first_name, :second_name, :email, :password, :password_confirmation, :remember_me, :token_creation_date)
    end

    def can_modify
      can_modify_base(params[:id])
    end

    def can_view_profile
      #Check user profile exists
      #If the profile is set to public then grant view
      #If the profile is set to registered then check logged in
      #If the profile is set to private then check can_modify
      user_to_view = User.find_by_id(params[:id])
      if user_to_view.nil?
        flash[:error] = I18n.t("user_groups.shared.errors.user")
        redirect_to main_app.root_url
        return
      end

      unless user_to_view.get_view_level==PROFILE_VIEW_LEVELS[1]
        return unless signed_in
        unless user_to_view.get_view_level==PROFILE_VIEW_LEVELS[2]
          unless (current_user.is_admin? || modifying_current_user?(user_to_view) )
            flash[:error] = I18n.t("user_groups.application.errors.permission")
            redirect_to main_app.root_url
            return
          end
        end
      end

      @user = user_to_view
    end

    def set_initials
      @first_letters = User.select("DISTINCT LOWER(SUBSTR(user_group_users.second_name, 1, 1)) AS name").order("name").collect{|fl| "#{fl.name}"}
    end
  end
end

app/views/user_group/users/partials/_group_table.html.erb
<h3><%= pluralize(user.groups.count, (t :'user_groups.views.users.show.membership')) %>:</h3>
<% if user.groups.count > 0 %>
    <table border="0" class="table">
        <tr>
            <th><%=(t :'user_groups.views.users.show.group')%></th>
            <th><%=(t :'user_groups.views.shared.join_date')%></th>
            <th><%=(t :'user_groups.views.users.show.leave') if allowed_edit %></th>
        </tr>
        <% groups = user.groups.order(SETTING_ORDER_GROUP).page(params[:page]) %>
        <%= paginate groups  %>
        <br />

        <%= render :partial => "user_group/users/partials/group_table_rows", collection: groups, as: :group, locals: { user: user, allowed_edit: allowed_edit} %>
    </table>
<% end %>

app/views/user_group/users/partials/_group_table_rows.html.erb
<% membership = group.memberships.find_by_user_id(user.id) %>
<tr>
    <td><%= link_to group.name.capitalize, groups_path %></td>
    <% if membership.approved? %>
        <td><%= membership.updated_at %></td>
    <% else %>
        <td><%= (t :'user_groups.views.shared.pending') %></td>
    <% end %>

    <td><%= (render partial: 'user_group/shared/leave_group_button', locals: {user: user, group: group}) if allowed_edit %></td>
</tr>

app/views/user_group/users/partials/_image.html.erb
<%# This file must figure out how to display a user profile
    Users have previously selected if they want to provide a url or gravatar name to their image.
    (If url it gets checked with fastimage to check validity before being saved)
    
    Concern: security issues? Javascript injection? what is a valid url etc
%>
<% unless user.image_link.nil? or user.image_link.blank? %>
    <% if user.image_link == SETTING_PROFILE_GRAVATAR_ID %>
        <% url = Gravatar.new(user.email).image_url %>
    <% elsif user.image_link.include?("http") || user.image_link.include?("www") %>
        <% url = user.image_link %>
    <% else %>
        <% url = SETTING_PROFILE_DEFAULT_PHOTO %>
    <% end %>

    <%= image_tag(url, :alt => (t :'user_groups.views.users.photo.alt_text'), :size => size, :class => "profile_image") %>
<% end %>