config/routes.rb
UserGroup::Engine.routes.draw do
  get '/',      to: 'static#home'
  get '/help',  to: 'static#help'
  get '/home',  to: 'static#home'
  get '/admin', to: 'static#admin'

  #root :to => 'static#home'

  devise_for :users, {
    :skip => [:registration, :omniauth_callbacks],
    class_name:     'UserGroup::User',
    module: :devise,
  }

  resources :users do
    get 'page/:page', :action => :index, :on => :collection
    member do
      post :create_token
      delete :destroy_token
    end
  end

  resources :groups do
    member do
        put :lock
        get :manage
    end

  end

  resources :memberships, only: [:create, :destroy] do
    member do
        put :approve
        put :approve_read
        delete :remove_read
    end
    collection do
        post :pending
    end
  end

end

app/models/user_group/authentication.rb
module UserGroup
  class UserGroup::Authentication < ActiveRecord::Base
    belongs_to :user
  end
end

app/models/user_group/group.rb
module UserGroup
  class NotPositiveIntegerValidator < ActiveModel::Validator
    def validate(record)
      record.errors[:name] << I18n.t("user_groups.groups.errors.validation") if record.name =~ /^[0-9]+$/
    end
  end

  class Group < ActiveRecord::Base
    has_many :memberships, dependent: :destroy
    has_many :users, -> { uniq }, through: :memberships

    #DB uniqueness is case insensitive
    before_save { self.name.downcase! }

    validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 40 }
    validates_with NotPositiveIntegerValidator
    validates :description, presence: true


    #is it ok having this public?
    def toggle_lock
      if self.is_locked
        self.is_locked = false
      else
        self.is_locked = true
      end
    end

    def full_memberships
      self.memberships.where("approved_by IS NOT NULL")
    end

    def pending_memberships
      self.memberships.where(approved_by: nil)
    end
  end
end

app/controllers/user_group/application_controller.rb
module UserGroup
  class ApplicationController < ::ApplicationController
    #protect_from_forgery
    before_filter :authenticate_user!

    protected
    def admin_users
      return unless signed_in
      unless current_user.is_admin?
        flash[:error] = I18n.t("user_groups.application.errors.admin")
        redirect_to(main_app.root_url)
      end
    end

    def collection_mgr_users
      return unless signed_in
      unless current_user.is_om? || current_user.is_cm? || current_user.is_admin?
        flash[:error] = I18n.t("user_groups.application.errors.permission")
        redirect_to(main_app.root_url)
      end
    end

    def modifying_current_user? (user_to_modify)
      return false unless current_user.id == user_to_modify.id
      return true
    end

    def can_modify_base(user_id)
      logger.debug "[TEMP] can_modify_base called on user_id: #{user_id}"
      user_to_modify = User.find_by_id(user_id)
      if user_to_modify.nil?
        flash[:error] = I18n.t("user_groups.shared.errors.user")
        redirect_to main_app.root_url
        return
      end

      return unless signed_in

      unless (current_user.is_admin? || modifying_current_user?(user_to_modify) )
        flash[:error] = I18n.t("user_groups.application.errors.permission")
        redirect_to main_app.root_url
        return
      end
      @user = user_to_modify
    end

    def signed_in
      unless user_signed_in? and !current_user.nil?
        flash[:error] = I18n.t("devise.failure.unauthenticated")
        redirect_to user_group.new_user_session_path
        return false
      end
      return true
    end

  end
end

app/controllers/user_group/groups_controller.rb
require_dependency "user_group/application_controller"

module UserGroup
  class GroupsController < ApplicationController
    before_filter :authenticate_user!
    before_filter :admin_users, except: [:index, :manage]

    def index
      @groups = Group.order(SETTING_ORDER_GROUP).page(params[:page])
    end

    def show
      @group = Group.find(params[:id])
    end

    def new
      @group = Group.new
    end

    def create
      @group = Group.new(group_params)
      if @group.valid? && @group.save
        flash[:success] = I18n.t("user_groups.groups.created")
        redirect_to @group
      else
        render 'new'
      end
    end

    def edit
      @group = Group.find(params[:id])
    end

    def manage
      @group = Group.find(params[:id])

      # Cannot manage special groups
      if @group.reader_group.nil? || @group.reader_group.eql?(false)
        flash[:error] = I18n.t("user_groups.application.errors.special_groups")
        redirect_to main_app.root_url
      end

      # Find the read access group for the group's collection
      result = ActiveFedora::SolrService.query("#{Solrizer.solr_name('read_access_group', :stored_searchable, type: :symbol)}:#{@group.name}")

      if result.count > 1
        flash[:error] = I18n.t("user_groups.application.errors.group_error")
        redirect_to main_app.root_url
      end

      @collection = SolrDocument.new(result.first)
      unless can? :manage_collection, @collection
        flash[:error] = I18n.t("user_groups.application.errors.manage_permission")
        redirect_to main_app.root_url
      end
    end

    def update
      @group = Group.find(params[:id])
      return if is_locked?(@group)
      if @group.update_attributes(group_params)
        flash[:success] = I18n.t("user_groups.shared.updated")
        redirect_to @group
      else
        render 'edit'
      end
    end

    def destroy
      deleting_group = Group.find(params[:id])
      return if is_locked?(deleting_group)
      deleting_group.destroy
      flash[:success] = I18n.t("user_groups.groups.deleted")
      redirect_to groups_path
    end

    def lock
      @group = Group.find(params[:id])
      @group.toggle_lock
      @group.save
      if @group.is_locked?
        redirect_to group_path @group
      else
        redirect_to edit_group_path @group
      end
    end

    private
    def group_params
      params.require(:group).permit(:name, :description, :is_locked)
    end

    def is_locked?(group)
      if group.is_locked?
        flash[:error] = I18n.t("user_groups.groups.errors.locked")
        redirect_to group
        return true
      end
      return false
    end
  end
end

app/controllers/user_group/memberships_controller.rb
require_dependency "user_group/application_controller"

module UserGroup
  class MembershipsController < ApplicationController
    before_filter :authenticate_user!
    before_filter :admin_users, only: [:create, :approve]
    #:can_modify (through can_modify_base) also sets @user (found by id ONLY)
    before_filter :can_modify, only: [:destroy]
    before_filter :collection_mgr_users, only: [:approve_read, :remove_read]
    #remote true sends requests in js
    respond_to :html, :js

    def create
      @user = get_user(params[:membership][:user_id])
      group_id = get_group_id(params[:membership][:group_id])

      if @user.nil?
        flash[:error] = I18n.t("user_groups.shared.errors.user")
      elsif group_id.nil?
        flash[:error] = I18n.t("user_groups.memberships.errors.group")
      else
        membership = @user.join_group(group_id)
        render 'users/edit' and return if membership.errors.count >0
        if(approve_membership(membership))
          flash[:success] = I18n.t("user_groups.memberships.joined")
        else
          flash[:error] = I18n.t("user_groups.memberships.errors.approving")
        end
      end
      redirect_to :back
    end

    def destroy
      group_id_or_name = params[:membership][:group_id]
      group = not_positive_integer?(group_id_or_name) ? Group.find_by_name(group_id_or_name.downcase) : Group.find_by_id(group_id_or_name)
      #Remove hardcoded registered
      action = @user.leave_group(group.id) unless group.nil? or group.name==SETTING_GROUP_DEFAULT
      if action.nil?
        flash[:error] = I18n.t("user_groups.memberships.errors.membership")
      else
        render 'users/edit' and return if action.errors.count >0
        flash[:success] = I18n.t("user_groups.memberships.leave")
      end
      redirect_to :back
    end

    def approve_read
      membership = Membership.find_by_id(params[:id])
      group = Group.find_by_id(membership.group_id)
      if group.reader_group.nil? || group.reader_group.eql?(false)
        flash[:error] = I18n.t("user_groups.application.errors.special_groups")
        redirect_to main_app.root_url
      end

      user = User.find_by_id(membership.user_id)

      result = ActiveFedora::SolrService.query("#{Solrizer.solr_name('read_access_group', :stored_searchable, type: :symbol)}:#{group.name}")

      if result.count > 1
        flash[:error] = I18n.t("user_groups.application.errors.group_error")
        redirect_to main_app.root_url
      end

      collection = SolrDocument.new(result.first)
      if can? :manage_collection, collection
        if(approve_membership(membership))
          flash[:success] = I18n.t("user_groups.memberships.approve")
          AuthMailer.approved_mail(user, group, collection[Solrizer.solr_name('title', :stored_searchable, type: :string)].first).deliver
        else
          flash[:error] = I18n.t("user_groups.memberships.errors.approving")
        end
      else
        flash[:error] = I18n.t("user_groups.application.errors.manage_permission")
      end
      redirect_to :back
    end

    def remove_read
      group_id_or_name = params[:membership][:group_id]
      group = not_positive_integer?(group_id_or_name) ? Group.find_by_name(group_id_or_name.downcase) : Group.find_by_id(group_id_or_name)
      user_id_or_email = params[:membership][:user_id]
      user = not_positive_integer?(user_id_or_email) ? User.find_by_id(user_id_or_email.downcase) : User.find_by_id(user_id_or_email)

      if group.reader_group.nil? || group.reader_group.eql?(false)
        flash[:error] = I18n.t("user_groups.application.errors.special_groups")
        redirect_to main_app.root_url
      end

      result = ActiveFedora::SolrService.query("#{Solrizer.solr_name('read_access_group', :stored_searchable, type: :symbol)}:#{group.name}")

      if result.count > 1
        flash[:error] = I18n.t("user_groups.application.errors.group_error")
        redirect_to main_app.root_url
      end

      collection = SolrDocument.new(result.first)
      if can? :manage_collection, collection
        action = user.leave_group(group.id) unless group.nil? or group.name==SETTING_GROUP_DEFAULT
        if action.nil?
          flash[:error] = I18n.t("user_groups.memberships.errors.membership")
        else
          render 'users/edit' and return if action.errors.count >0
          flash[:success] = I18n.t("user_groups.memberships.leave")
        end
        redirect_to :back
      else
        flash[:error] = I18n.t("user_groups.application.errors.manage_permission")
        redirect_to main_app.root_url
      end
    end

    def approve
      membership = Membership.find_by_id(params[:id])
      if(approve_membership(membership))
        flash[:success] = I18n.t("user_groups.memberships.approve")
      else
        flash[:error] = I18n.t("user_groups.memberships.errors.approving")
      end
      redirect_to :back
    end

    #Similar to create
    def pending
      @user = get_user(params[:membership][:user_id])
      group = get_group(params[:membership][:group_id])

      if @user.nil?
        flash[:error] = I18n.t("user_groups.shared.errors.user")
      elsif group.id.nil?
        flash[:error] = I18n.t("user_groups.memberships.errors.group")
      else
        action = @user.join_group(group.id)
        render 'groups/index' and return if action.errors.count >0

        # inform managers for reader group requests
        if group.reader_group.present? && group.reader_group.eql?(true)
          result = ActiveFedora::SolrService.query("id:#{group.name}")
          doc = SolrDocument.new(result.pop) if result.count > 0
          managers = doc[Solrizer.solr_name('manager_access_person', :stored_searchable, type: :symbol)]

          # if no manager set for this collection it could be inherited, iterate up the tree
          if managers.nil?
            doc[Solrizer.solr_name('ancestor_id', :stored_searchable, type: :text)].reverse_each do |ancestor|
              result = ActiveFedora::SolrService.query("id:#{ancestor}")
              ancestordoc = SolrDocument.new(result.pop) if result.count > 0
              managers = ancestordoc[Solrizer.solr_name('manager_access_person', :stored_searchable, type: :symbol)]
              break if managers.present? && managers.count > 0
            end
          end

          if managers.present? && managers.count > 0
            AuthMailer.pending_mail(managers, @user.email, user_group.manage_group_url(group)).deliver
          end
        end

        flash[:success] = I18n.t("user_groups.memberships.pending")
      end
      redirect_to :back
    end


    private
    def can_modify
      can_modify_base(params[:membership][:user_id])
    end

    def approve_membership(application)
      unless application.nil?
        application.approve_membership(current_user.id)
        application.save
        return true
      end
      return false
    end

    def get_user(user_id_or_name)
      return not_positive_integer?(user_id_or_name) ? User.find_by_email(user_id_or_name) : User.find_by_id(user_id_or_name)
    end

    def get_group_id(group_id_or_name)
      return not_positive_integer?(group_id_or_name) ? get_group_id_from_group_name(group_id_or_name) : group_id_or_name
    end

    def get_group(group_id_or_name)
      return group = Group.find(not_positive_integer?(group_id_or_name) ? get_group_id_from_group_name(group_id_or_name) : group_id_or_name)
    end

    def get_group_id_from_group_name(group_name)
      group = Group.find_by_name(group_name.downcase)
      return group.id unless group.nil?
    end

    def not_positive_integer?(string)
      return true unless string =~ /^[0-9]+$/
    end
  end
end

app/controllers/user_group/omniauth_callbacks_controller.rb
module UserGroup
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
    def shibboleth
      find_or_create_user('shibboleth')
    end

    def find_or_create_user(auth_type)
      omniauth = request.env['omniauth.auth']

      authentication = UserGroup::Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
      if authentication
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => auth_type
        sign_in authentication.user, :event => :authentication
        redirect_to main_app.root_path
      elsif current_user
        current_user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => auth_type
        redirect_to main_app.root_path       
      else
        if create_user(auth_type, omniauth)
          flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => auth_type
          sign_in @user, :event => :authentication
          redirect_to main_app.root_path
        else
          errors = @user.errors.full_messages.join(", ").html_safe
          flash[:alert] = I18n.t("user_groups.users.errors.missing_account_details", :reason => errors)
          session[:omniauth] = omniauth.except('extra')
          redirect_to new_user_path || main_app.root_path 
        end
      end
    end

    protected :find_or_create_user

    private
  
      def create_user(auth_type, omniauth)
        create_method = "create_for_#{auth_type.downcase}".to_sym
        @user = UserGroup::User.send(create_method, omniauth)

        if @user.save
          # join registered group
          group = UserGroup::Group.where(name: SETTING_GROUP_DEFAULT, description: "Every user account is a member of this group.", is_locked: true).first_or_create
          if group
            membership = @user.join_group(group.id)
            membership.approve_membership(@user.id)
            membership.save
          end
          return true
        else
          return false
        end
      end

  end
end

app/controllers/user_group/static_controller.rb
require_dependency "user_group/application_controller"

module UserGroup
  class StaticController < ApplicationController
    before_filter :authenticate_user!
    before_filter :admin_users, only: [:admin]

    def home
    end

    def help
    end

    def admin
    end
  end
end

app/helpers/user_group/application_helper.rb
module UserGroup
  module ApplicationHelper
    #http://www.candland.net/2012/04/17/rails-routes-used-in-an-isolated-engine/
    def method_missing method, *args, &block
      #puts "LOOKING FOR ROUTES #{method}"
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          main_app.send(method, *args)
        else
          super
        end
      else
        super
      end
    end

    def respond_to?(method)
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          true
        else
          super
        end
      else
        super
      end
    end

  end
end

app/helpers/user_group/groups_helper.rb
module UserGroup
  module GroupsHelper
    #does not really seem to be a helper
    def pending_users_count(group)
      group.pending_memberships.count
    end
  end
end

app/helpers/user_group/static_helper.rb
#Delete this file?
module UserGroup
  module StaticHelper
  end
end

app/views/user_group/groups/_delete_link.html.erb
<% unless group.is_locked %>
    <h3><%= (t :'user_groups.views.groups.edit.delete') %></h3>
    <%= link_to (t :'user_groups.views.shared.delete'), group, method: :delete, confirm: (t :'user_groups.views.shared.confirm') %>
<% end %>

app/views/user_group/groups/_locked_link.html.erb
<p><%= (t :'user_groups.views.groups.edit.locked') %></p>
<%= link_to (t :'user_groups.views.groups.edit.unlock'), lock_group_path(group), method: :put %>

app/views/user_group/groups/_pending_link.html.erb
<% amount_pending = pending_users_count(group) %>
<% if amount_pending >0 %>
    <%= link_to (t :'user_groups.views.groups.index.pending2'), edit_group_path(group) %>
    <%= amount_pending %>
    <br />            
<% end %>

app/views/user_group/groups/_user_table.html.erb
<h3><%= pluralize(group.users.count, (t :'user_groups.views.groups.show.member')) %>:</h3>
<% if group.users.count > 0 %>
    <table border="0" class="table">
        <tr>
            <th><%= (t :'user_groups.views.shared.name') %></th>
            <th><%= (t :'user_groups.views.shared.join_date') %></th>
            <th><%= (t :'user_groups.views.groups.show.approve') %></th>
        </tr>
        <% users = group.users.order(SETTING_ORDER_USER).page(params[:page]) %>
        <%= paginate users  %>
        <br />

        <%= render :partial => "user_table_rows", collection: users, as: :user %>
    </table>
<% end %>

app/views/user_group/groups/_user_table_rows.html.erb
<tr>
    <td><%= link_to user.full_name, user_path(user) %></td>
    <td><%= user.updated_at %></td>

    <% membership = user.memberships.find_by_group_id(@group.id) %>
    <% if membership.approved? %>
        <% approving_user = UserGroup::User.find_by_id(membership.approved_by) %>
        <td><%= (link_to approving_user.full_name, user_path(approving_user)) unless approving_user.nil? %></td>
    <% else %>
        <td> <%= (t :'user_groups.views.shared.pending') %><%#=link_to "Approve?", approve_membership_path(membership), method: :put %></td>
    <% end %>
</tr>

app/views/user_group/groups/edit.html.erb
<%= render partial: "user_group/shared/header" %>

<%= form_for(@group) do |f| %>
    <div><%= link_to (t :'user_groups.views.shared.back'), @group %></div><br />

    <%= render partial: 'user_group/shared/error_messages', locals: {object: f.object} %>
    <% if @group.is_locked %>
        <h2 class="no_bottom_margin"><%= @group.name.capitalize %></h2>
        <%= render partial: "locked_link", locals: {group: @group}  %>
    <% else %>
        <div><%= f.label :name, (t :'user_groups.views.shared.name')%><br />
        <%= f.text_field :name , value: @group.name.capitalize %></div>

        <div><%= f.label :description, (t :'user_groups.views.shared.description') %><br />
        <%= f.text_field :description %></div>

        <div><%= f.submit (t :'user_groups.views.groups.edit.update') %></div>
        <br />
        <%= link_to (t :'user_groups.views.groups.edit.lock'),lock_group_path(@group), method: :put, confirm: (t :'user_groups.views.groups.edit.lock_confirm') %>
    <% end %>
<% end %>

<%= render partial: "delete_link", locals: {group: @group} %>

<br />



<h3><%= (t :'user_groups.views.shared.group_membership') %></h3>
<% #Rendering the other way does odd things %>
<h4 class="no_bottom_margin"><%= (t :'user_groups.views.shared.remove') %></h4>
<%= render partial: 'user_group/shared/leave_groups', locals: {object: @group} %>
<h4 class="no_bottom_margin"><%= (t :'user_groups.views.shared.pending') %></h4>
<%= render partial: 'user_group/shared/pending_groups', locals: {object: @group} %>
<h4 class="no_bottom_margin"><%= (t :'user_groups.views.shared.add') %></h4>
<%= render partial: 'user_group/shared/join_groups', locals: {object: @group} %>

app/views/user_group/groups/index.html.erb
<%= render partial: "user_group/shared/header" %>

<%= render partial: "user_group/shared/load_user_or_admin_view",
    locals: { prefix: "user_group/groups", name: "index" } %>

app/views/user_group/groups/manage.html.erb
<h3><%= (t :'user_groups.views.shared.manage_read_group', :collection_id => @collection.id, :collection_name => @collection['title_tesim'].first) %></h3>
<% #Rendering the other way does odd things %>
<h4 class="no_bottom_margin"><%= (t :'user_groups.views.shared.remove') %></h4>
<%= render partial: 'user_group/shared/remove_read', locals: {object: @group} %>
<h4 class="no_bottom_margin"><%= (t :'user_groups.views.shared.pending') %></h4>
<%= render partial: 'user_group/shared/pending_read', locals: {object: @group} %>

app/views/user_group/groups/new.html.erb
<%= render :partial => "user_group/shared/header" %>

<h2><%= (t :'user_groups.views.groups.new.heading') %></h2>

<%= form_for(@group) do |f| %>
    <%= render 'user_group/shared/error_messages', object: f.object %>

    <div><%= f.label :name, (t :'user_groups.views.shared.name') %><br />
    <%= f.text_field :name %></div>

    <div><%= f.label :description, (t :'user_groups.views.shared.description') %><br />
    <%= f.text_field :description %></div>

  <div><%= f.submit t :'user_groups.views.groups.new.create' %></div>
<% end %>

app/views/user_group/groups/show.html.erb
<%= render partial: "user_group/shared/header" %>

<div><%= link_to (t :'user_groups.views.shared.groups'), groups_path %></div>
<h2 class="no_bottom_margin"><%= @group.name.capitalize %></h2>
<div class="tab"><%= @group.description %></div>

<%= render partial: "user_group/shared/updated_at", locals:{ object: @group} %>

<div class="clear"></div>
<br />
<%= link_to (t :'user_groups.views.groups.show.edit'), edit_group_path %>
<br />

<%= render partial: "user_table", locals: {group: @group} %>